server {
    listen 80;
    server_name recuperadespliegue.com;
    root /usr/share/nginx/html/RecuperacionDespliegue;
    index index.html;

    location /imagenes {
        proxy_pass http://localhost:8080/imagenes/;
        proxy_set_header Host $host;
    }

    location /auth {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;
    }

    location /solotu {
        allow 192.168.0.100;
        deny all;
    }

    location /youtube {
        return 301 https://www.youtube.com/;
    }
}

server {
    listen 443 ssl;
    server_name examendespliegue.com;
    ssl_certificate /etc/ssl/certs/autocert.crt;
    ssl_certificate_key /etc/ssl/private/autocert.key;
    root /usr/share/nginx/html/RecuperacionDespliegue;
    index index.html;
}
